FROM ngrok/ngrok as dep_ngrok

FROM alpine:3.17

WORKDIR /workspace

RUN apk --no-cache add curl
RUN apk --no-cache add jq
RUN apk --no-cache add go
RUN apk --no-cache add bash
COPY --from=dep_ngrok /bin/ngrok /bin/ngrok
