// Code generated by go-swagger; DO NOT EDIT.

package service_plugin_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteLootBoxPluginConfig1Reader is a Reader for the DeleteLootBoxPluginConfig1 structure.
type DeleteLootBoxPluginConfig1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteLootBoxPluginConfig1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteLootBoxPluginConfig1NoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteLootBoxPluginConfig1NoContent creates a DeleteLootBoxPluginConfig1NoContent with default headers values
func NewDeleteLootBoxPluginConfig1NoContent() *DeleteLootBoxPluginConfig1NoContent {
	return &DeleteLootBoxPluginConfig1NoContent{}
}

/*
DeleteLootBoxPluginConfig1NoContent describes a response with status code 204, with default header values.

Delete successfully
*/
type DeleteLootBoxPluginConfig1NoContent struct {
}

// IsSuccess returns true when this delete loot box plugin config1 no content response has a 2xx status code
func (o *DeleteLootBoxPluginConfig1NoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete loot box plugin config1 no content response has a 3xx status code
func (o *DeleteLootBoxPluginConfig1NoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete loot box plugin config1 no content response has a 4xx status code
func (o *DeleteLootBoxPluginConfig1NoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete loot box plugin config1 no content response has a 5xx status code
func (o *DeleteLootBoxPluginConfig1NoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete loot box plugin config1 no content response a status code equal to that given
func (o *DeleteLootBoxPluginConfig1NoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete loot box plugin config1 no content response
func (o *DeleteLootBoxPluginConfig1NoContent) Code() int {
	return 204
}

func (o *DeleteLootBoxPluginConfig1NoContent) Error() string {
	return fmt.Sprintf("[DELETE /admin/namespaces/{namespace}/revocation/plugins/revocation][%d] deleteLootBoxPluginConfig1NoContent ", 204)
}

func (o *DeleteLootBoxPluginConfig1NoContent) String() string {
	return fmt.Sprintf("[DELETE /admin/namespaces/{namespace}/revocation/plugins/revocation][%d] deleteLootBoxPluginConfig1NoContent ", 204)
}

func (o *DeleteLootBoxPluginConfig1NoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
