// Code generated by go-swagger; DO NOT EDIT.

package service_plugin_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteLootBoxPluginConfig1Params creates a new DeleteLootBoxPluginConfig1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteLootBoxPluginConfig1Params() *DeleteLootBoxPluginConfig1Params {
	return &DeleteLootBoxPluginConfig1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteLootBoxPluginConfig1ParamsWithTimeout creates a new DeleteLootBoxPluginConfig1Params object
// with the ability to set a timeout on a request.
func NewDeleteLootBoxPluginConfig1ParamsWithTimeout(timeout time.Duration) *DeleteLootBoxPluginConfig1Params {
	return &DeleteLootBoxPluginConfig1Params{
		timeout: timeout,
	}
}

// NewDeleteLootBoxPluginConfig1ParamsWithContext creates a new DeleteLootBoxPluginConfig1Params object
// with the ability to set a context for a request.
func NewDeleteLootBoxPluginConfig1ParamsWithContext(ctx context.Context) *DeleteLootBoxPluginConfig1Params {
	return &DeleteLootBoxPluginConfig1Params{
		Context: ctx,
	}
}

// NewDeleteLootBoxPluginConfig1ParamsWithHTTPClient creates a new DeleteLootBoxPluginConfig1Params object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteLootBoxPluginConfig1ParamsWithHTTPClient(client *http.Client) *DeleteLootBoxPluginConfig1Params {
	return &DeleteLootBoxPluginConfig1Params{
		HTTPClient: client,
	}
}

/*
DeleteLootBoxPluginConfig1Params contains all the parameters to send to the API endpoint

	for the delete loot box plugin config 1 operation.

	Typically these are written to a http.Request.
*/
type DeleteLootBoxPluginConfig1Params struct {

	// Namespace.
	Namespace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete loot box plugin config 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteLootBoxPluginConfig1Params) WithDefaults() *DeleteLootBoxPluginConfig1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete loot box plugin config 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteLootBoxPluginConfig1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete loot box plugin config 1 params
func (o *DeleteLootBoxPluginConfig1Params) WithTimeout(timeout time.Duration) *DeleteLootBoxPluginConfig1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete loot box plugin config 1 params
func (o *DeleteLootBoxPluginConfig1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete loot box plugin config 1 params
func (o *DeleteLootBoxPluginConfig1Params) WithContext(ctx context.Context) *DeleteLootBoxPluginConfig1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete loot box plugin config 1 params
func (o *DeleteLootBoxPluginConfig1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete loot box plugin config 1 params
func (o *DeleteLootBoxPluginConfig1Params) WithHTTPClient(client *http.Client) *DeleteLootBoxPluginConfig1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete loot box plugin config 1 params
func (o *DeleteLootBoxPluginConfig1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNamespace adds the namespace to the delete loot box plugin config 1 params
func (o *DeleteLootBoxPluginConfig1Params) WithNamespace(namespace string) *DeleteLootBoxPluginConfig1Params {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the delete loot box plugin config 1 params
func (o *DeleteLootBoxPluginConfig1Params) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteLootBoxPluginConfig1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
