// Code generated by go-swagger; DO NOT EDIT.

package service_plugin_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"revocation-grpc-plugin-server-go-cli/pkg/client/platformservice/openapi2/models"
)

// NewUpdateLootBoxPluginConfig1Params creates a new UpdateLootBoxPluginConfig1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateLootBoxPluginConfig1Params() *UpdateLootBoxPluginConfig1Params {
	return &UpdateLootBoxPluginConfig1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateLootBoxPluginConfig1ParamsWithTimeout creates a new UpdateLootBoxPluginConfig1Params object
// with the ability to set a timeout on a request.
func NewUpdateLootBoxPluginConfig1ParamsWithTimeout(timeout time.Duration) *UpdateLootBoxPluginConfig1Params {
	return &UpdateLootBoxPluginConfig1Params{
		timeout: timeout,
	}
}

// NewUpdateLootBoxPluginConfig1ParamsWithContext creates a new UpdateLootBoxPluginConfig1Params object
// with the ability to set a context for a request.
func NewUpdateLootBoxPluginConfig1ParamsWithContext(ctx context.Context) *UpdateLootBoxPluginConfig1Params {
	return &UpdateLootBoxPluginConfig1Params{
		Context: ctx,
	}
}

// NewUpdateLootBoxPluginConfig1ParamsWithHTTPClient creates a new UpdateLootBoxPluginConfig1Params object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateLootBoxPluginConfig1ParamsWithHTTPClient(client *http.Client) *UpdateLootBoxPluginConfig1Params {
	return &UpdateLootBoxPluginConfig1Params{
		HTTPClient: client,
	}
}

/*
UpdateLootBoxPluginConfig1Params contains all the parameters to send to the API endpoint

	for the update loot box plugin config 1 operation.

	Typically these are written to a http.Request.
*/
type UpdateLootBoxPluginConfig1Params struct {

	// Body.
	Body *models.RevocationPluginConfigUpdate

	// Namespace.
	Namespace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update loot box plugin config 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateLootBoxPluginConfig1Params) WithDefaults() *UpdateLootBoxPluginConfig1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update loot box plugin config 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateLootBoxPluginConfig1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update loot box plugin config 1 params
func (o *UpdateLootBoxPluginConfig1Params) WithTimeout(timeout time.Duration) *UpdateLootBoxPluginConfig1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update loot box plugin config 1 params
func (o *UpdateLootBoxPluginConfig1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update loot box plugin config 1 params
func (o *UpdateLootBoxPluginConfig1Params) WithContext(ctx context.Context) *UpdateLootBoxPluginConfig1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update loot box plugin config 1 params
func (o *UpdateLootBoxPluginConfig1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update loot box plugin config 1 params
func (o *UpdateLootBoxPluginConfig1Params) WithHTTPClient(client *http.Client) *UpdateLootBoxPluginConfig1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update loot box plugin config 1 params
func (o *UpdateLootBoxPluginConfig1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update loot box plugin config 1 params
func (o *UpdateLootBoxPluginConfig1Params) WithBody(body *models.RevocationPluginConfigUpdate) *UpdateLootBoxPluginConfig1Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update loot box plugin config 1 params
func (o *UpdateLootBoxPluginConfig1Params) SetBody(body *models.RevocationPluginConfigUpdate) {
	o.Body = body
}

// WithNamespace adds the namespace to the update loot box plugin config 1 params
func (o *UpdateLootBoxPluginConfig1Params) WithNamespace(namespace string) *UpdateLootBoxPluginConfig1Params {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the update loot box plugin config 1 params
func (o *UpdateLootBoxPluginConfig1Params) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateLootBoxPluginConfig1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
