// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.9
// source: revocation.proto

package revocation_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Revocation_Revoke_FullMethodName = "/accelbyte.platform.revocation.v1.Revocation/Revoke"
)

// RevocationClient is the client API for Revocation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RevocationClient interface {
	// *
	// Revoke
	// Currently, only Third-Party DLC Refund and Refund Order will trigger this grpc revocation.
	Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error)
}

type revocationClient struct {
	cc grpc.ClientConnInterface
}

func NewRevocationClient(cc grpc.ClientConnInterface) RevocationClient {
	return &revocationClient{cc}
}

func (c *revocationClient) Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeResponse)
	err := c.cc.Invoke(ctx, Revocation_Revoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RevocationServer is the server API for Revocation service.
// All implementations should embed UnimplementedRevocationServer
// for forward compatibility.
type RevocationServer interface {
	// *
	// Revoke
	// Currently, only Third-Party DLC Refund and Refund Order will trigger this grpc revocation.
	Revoke(context.Context, *RevokeRequest) (*RevokeResponse, error)
}

// UnimplementedRevocationServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRevocationServer struct{}

func (UnimplementedRevocationServer) Revoke(context.Context, *RevokeRequest) (*RevokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Revoke not implemented")
}
func (UnimplementedRevocationServer) testEmbeddedByValue() {}

// UnsafeRevocationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RevocationServer will
// result in compilation errors.
type UnsafeRevocationServer interface {
	mustEmbedUnimplementedRevocationServer()
}

func RegisterRevocationServer(s grpc.ServiceRegistrar, srv RevocationServer) {
	// If the following call pancis, it indicates UnimplementedRevocationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Revocation_ServiceDesc, srv)
}

func _Revocation_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RevocationServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Revocation_Revoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RevocationServer).Revoke(ctx, req.(*RevokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Revocation_ServiceDesc is the grpc.ServiceDesc for Revocation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Revocation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.platform.revocation.v1.Revocation",
	HandlerType: (*RevocationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Revoke",
			Handler:    _Revocation_Revoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "revocation.proto",
}
