// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: revocation.proto

package revocation_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Revoke Request
// revokeEntryType:
// 1. ITEM: Revoke by this item
// Example:
// - Admin Config durable entitlement revocation strategy to CUSTOM
// - Admin Refund an Order and this order's item is a bundle, contains item-durable-1 item-consumable-2
// - AB will only send item-durable-1 revoke request
// 2. ENTITLEMENT: Revoke a specific entitlement directly
// 3. CURRENCY: Revoke certain amount of VC directly
type RevokeRequest struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	RevokeEntryType string                   `protobuf:"bytes,1,opt,name=revokeEntryType,proto3" json:"revokeEntryType,omitempty"` // ITEM, ENTITLEMENT, CURRENCY
	UserId          string                   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Namespace       string                   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Quantity        int32                    `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`      // The quantity of revoke entry.
	Item            *RevokeItemObject        `protobuf:"bytes,5,opt,name=item,proto3" json:"item,omitempty"`               // empty if revoke entry type is not ITEM
	Entitlement     *RevokeEntitlementObject `protobuf:"bytes,6,opt,name=entitlement,proto3" json:"entitlement,omitempty"` // empty if revoke entry type is not ENTITLEMENT
	Currency        *RevokeCurrencyObject    `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`       // empty if revoke entry type is not CURRENCY
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_revocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_revocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_revocation_proto_rawDescGZIP(), []int{0}
}

func (x *RevokeRequest) GetRevokeEntryType() string {
	if x != nil {
		return x.RevokeEntryType
	}
	return ""
}

func (x *RevokeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RevokeRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *RevokeRequest) GetItem() *RevokeItemObject {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *RevokeRequest) GetEntitlement() *RevokeEntitlementObject {
	if x != nil {
		return x.Entitlement
	}
	return nil
}

func (x *RevokeRequest) GetCurrency() *RevokeCurrencyObject {
	if x != nil {
		return x.Currency
	}
	return nil
}

type RevokeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // SUCCESS/FAIL
	Reason           string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	CustomRevocation map[string]string      `protobuf:"bytes,3,rep,name=customRevocation,proto3" json:"customRevocation,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // custom revocation details.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RevokeResponse) Reset() {
	*x = RevokeResponse{}
	mi := &file_revocation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeResponse) ProtoMessage() {}

func (x *RevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_revocation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeResponse.ProtoReflect.Descriptor instead.
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return file_revocation_proto_rawDescGZIP(), []int{1}
}

func (x *RevokeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RevokeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RevokeResponse) GetCustomRevocation() map[string]string {
	if x != nil {
		return x.CustomRevocation
	}
	return nil
}

type RevokeItemObject struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ItemId          string                 `protobuf:"bytes,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	ItemSku         string                 `protobuf:"bytes,2,opt,name=itemSku,proto3" json:"itemSku,omitempty"`
	ItemType        string                 `protobuf:"bytes,3,opt,name=itemType,proto3" json:"itemType,omitempty"`
	UseCount        int32                  `protobuf:"varint,4,opt,name=useCount,proto3" json:"useCount,omitempty"`
	EntitlementType string                 `protobuf:"bytes,5,opt,name=entitlementType,proto3" json:"entitlementType,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RevokeItemObject) Reset() {
	*x = RevokeItemObject{}
	mi := &file_revocation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeItemObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeItemObject) ProtoMessage() {}

func (x *RevokeItemObject) ProtoReflect() protoreflect.Message {
	mi := &file_revocation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeItemObject.ProtoReflect.Descriptor instead.
func (*RevokeItemObject) Descriptor() ([]byte, []int) {
	return file_revocation_proto_rawDescGZIP(), []int{2}
}

func (x *RevokeItemObject) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *RevokeItemObject) GetItemSku() string {
	if x != nil {
		return x.ItemSku
	}
	return ""
}

func (x *RevokeItemObject) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *RevokeItemObject) GetUseCount() int32 {
	if x != nil {
		return x.UseCount
	}
	return 0
}

func (x *RevokeItemObject) GetEntitlementType() string {
	if x != nil {
		return x.EntitlementType
	}
	return ""
}

type RevokeEntitlementObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntitlementId string                 `protobuf:"bytes,1,opt,name=entitlementId,proto3" json:"entitlementId,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Sku           string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeEntitlementObject) Reset() {
	*x = RevokeEntitlementObject{}
	mi := &file_revocation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeEntitlementObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeEntitlementObject) ProtoMessage() {}

func (x *RevokeEntitlementObject) ProtoReflect() protoreflect.Message {
	mi := &file_revocation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeEntitlementObject.ProtoReflect.Descriptor instead.
func (*RevokeEntitlementObject) Descriptor() ([]byte, []int) {
	return file_revocation_proto_rawDescGZIP(), []int{3}
}

func (x *RevokeEntitlementObject) GetEntitlementId() string {
	if x != nil {
		return x.EntitlementId
	}
	return ""
}

func (x *RevokeEntitlementObject) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *RevokeEntitlementObject) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

type RevokeCurrencyObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	CurrencyCode  string                 `protobuf:"bytes,2,opt,name=currencyCode,proto3" json:"currencyCode,omitempty"`
	BalanceOrigin string                 `protobuf:"bytes,3,opt,name=balanceOrigin,proto3" json:"balanceOrigin,omitempty"` // Playstation, Xbox, Steam, Epic, IOS, GooglePlay, Twitch, Nintendo, System, Other
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCurrencyObject) Reset() {
	*x = RevokeCurrencyObject{}
	mi := &file_revocation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCurrencyObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCurrencyObject) ProtoMessage() {}

func (x *RevokeCurrencyObject) ProtoReflect() protoreflect.Message {
	mi := &file_revocation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCurrencyObject.ProtoReflect.Descriptor instead.
func (*RevokeCurrencyObject) Descriptor() ([]byte, []int) {
	return file_revocation_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeCurrencyObject) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RevokeCurrencyObject) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *RevokeCurrencyObject) GetBalanceOrigin() string {
	if x != nil {
		return x.BalanceOrigin
	}
	return ""
}

var File_revocation_proto protoreflect.FileDescriptor

const file_revocation_proto_rawDesc = "" +
	"\n" +
	"\x10revocation.proto\x12 accelbyte.platform.revocation.v1\"\x84\x03\n" +
	"\rRevokeRequest\x12(\n" +
	"\x0frevokeEntryType\x18\x01 \x01(\tR\x0frevokeEntryType\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12F\n" +
	"\x04item\x18\x05 \x01(\v22.accelbyte.platform.revocation.v1.RevokeItemObjectR\x04item\x12[\n" +
	"\ventitlement\x18\x06 \x01(\v29.accelbyte.platform.revocation.v1.RevokeEntitlementObjectR\ventitlement\x12R\n" +
	"\bcurrency\x18\a \x01(\v26.accelbyte.platform.revocation.v1.RevokeCurrencyObjectR\bcurrency\"\xf9\x01\n" +
	"\x0eRevokeResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12r\n" +
	"\x10customRevocation\x18\x03 \x03(\v2F.accelbyte.platform.revocation.v1.RevokeResponse.CustomRevocationEntryR\x10customRevocation\x1aC\n" +
	"\x15CustomRevocationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x01\n" +
	"\x10RevokeItemObject\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\tR\x06itemId\x12\x18\n" +
	"\aitemSku\x18\x02 \x01(\tR\aitemSku\x12\x1a\n" +
	"\bitemType\x18\x03 \x01(\tR\bitemType\x12\x1a\n" +
	"\buseCount\x18\x04 \x01(\x05R\buseCount\x12(\n" +
	"\x0fentitlementType\x18\x05 \x01(\tR\x0fentitlementType\"i\n" +
	"\x17RevokeEntitlementObject\x12$\n" +
	"\rentitlementId\x18\x01 \x01(\tR\rentitlementId\x12\x16\n" +
	"\x06itemId\x18\x02 \x01(\tR\x06itemId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\"~\n" +
	"\x14RevokeCurrencyObject\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\"\n" +
	"\fcurrencyCode\x18\x02 \x01(\tR\fcurrencyCode\x12$\n" +
	"\rbalanceOrigin\x18\x03 \x01(\tR\rbalanceOrigin2y\n" +
	"\n" +
	"Revocation\x12k\n" +
	"\x06Revoke\x12/.accelbyte.platform.revocation.v1.RevokeRequest\x1a0.accelbyte.platform.revocation.v1.RevokeResponseB\x82\x01\n" +
	"$net.accelbyte.platform.revocation.v1B\x0frevocationProtoP\x01Z$accelbyte.net/platform/revocation_v1\xaa\x02 Accelbyte.Platform.revocation.V1b\x06proto3"

var (
	file_revocation_proto_rawDescOnce sync.Once
	file_revocation_proto_rawDescData []byte
)

func file_revocation_proto_rawDescGZIP() []byte {
	file_revocation_proto_rawDescOnce.Do(func() {
		file_revocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_revocation_proto_rawDesc), len(file_revocation_proto_rawDesc)))
	})
	return file_revocation_proto_rawDescData
}

var file_revocation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_revocation_proto_goTypes = []any{
	(*RevokeRequest)(nil),           // 0: accelbyte.platform.revocation.v1.RevokeRequest
	(*RevokeResponse)(nil),          // 1: accelbyte.platform.revocation.v1.RevokeResponse
	(*RevokeItemObject)(nil),        // 2: accelbyte.platform.revocation.v1.RevokeItemObject
	(*RevokeEntitlementObject)(nil), // 3: accelbyte.platform.revocation.v1.RevokeEntitlementObject
	(*RevokeCurrencyObject)(nil),    // 4: accelbyte.platform.revocation.v1.RevokeCurrencyObject
	nil,                             // 5: accelbyte.platform.revocation.v1.RevokeResponse.CustomRevocationEntry
}
var file_revocation_proto_depIdxs = []int32{
	2, // 0: accelbyte.platform.revocation.v1.RevokeRequest.item:type_name -> accelbyte.platform.revocation.v1.RevokeItemObject
	3, // 1: accelbyte.platform.revocation.v1.RevokeRequest.entitlement:type_name -> accelbyte.platform.revocation.v1.RevokeEntitlementObject
	4, // 2: accelbyte.platform.revocation.v1.RevokeRequest.currency:type_name -> accelbyte.platform.revocation.v1.RevokeCurrencyObject
	5, // 3: accelbyte.platform.revocation.v1.RevokeResponse.customRevocation:type_name -> accelbyte.platform.revocation.v1.RevokeResponse.CustomRevocationEntry
	0, // 4: accelbyte.platform.revocation.v1.Revocation.Revoke:input_type -> accelbyte.platform.revocation.v1.RevokeRequest
	1, // 5: accelbyte.platform.revocation.v1.Revocation.Revoke:output_type -> accelbyte.platform.revocation.v1.RevokeResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_revocation_proto_init() }
func file_revocation_proto_init() {
	if File_revocation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_revocation_proto_rawDesc), len(file_revocation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_revocation_proto_goTypes,
		DependencyIndexes: file_revocation_proto_depIdxs,
		MessageInfos:      file_revocation_proto_msgTypes,
	}.Build()
	File_revocation_proto = out.File
	file_revocation_proto_goTypes = nil
	file_revocation_proto_depIdxs = nil
}
